### ISSUE TITLE
dissertations notebook stop auto download 

### ISSUE THREAD

**Issue by ArtemisLav** [cernanalysispreservation/freya-pid-notebooks-showcase#5]
The `FREYA PID Graph - Dissertations` notebook automatically downloads a .bib file when clicked on.

**Comment by pamfilos** [comment]
closing as fixed with https://github.com/cernanalysispreservation/freya-pid-notebooks-showcase/commit/f4405d1d4def16efaa55a6d67b45d0d8f82a07a4
